version: 0.2

phases:
  install:
    runtime-versions:
      terraform: 1.0.0

  build:
    commands:
      - cd aws-terraform-v1/
      - terraform init
      - terraform validate
      - terraform plan -out=tfplan

  post_build:
    commands:
      - terraform apply -auto-approve tfplan
