version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "cd $CODEBUILD_SRC_DIR"
      - cd aws-terraform-v1/

  pre_build:
    commands:
      - aws s3 cp s3://gitea-artifact-tf/tfplan tfplan
      - terraform init
      - terraform validate

  build:
    commands:
      - |
        if aws elasticbeanstalk describe-applications --application-names Gitea-Application --region eu-west-2 > /dev/null 2>&1; then
          echo "Elastic Beanstalk application 'Gitea-Application' already exists. Skipping deploy stage."
          exit 0  # Skip deploy stage
        else
          echo "Elastic Beanstalk application 'Gitea-Application' does not exist. Proceeding with deploy stage."
          # Proceed with deployment
          
      - terraform apply -auto-approve tfplan


  post_build:
    commands:
      - echo "Deployed, go and check that out!"
