version: "3"

networks:
  gitea:
    external: false

services:
  server:
    build: .
    container_name: new-gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db
      - GITEA__database__NAME=${DBNAME}
      - GITEA__database__USER=${NAME}
      - GITEA__database__PASSWD=${PASS}
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASS}
      - MYSQL_USER=${NAME}
      - MYSQL_PASSWORD=${PASS}
      - MYSQL_DATABASE=${DBNAME}
    networks:
      - gitea
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local
