apiVersion: v1
kind: Service
metadata:
  name: gitea-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
  selector:
    app: gitea
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
        - name: gitea-container
          image: ghcr.io/sofiia-an/gitea-app-ghcr:latest
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: DATABASE 
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD

          ports:
            - containerPort: 3000
              name: gitea
